package me.skidrunner.ann;

public enum Function {
	IDENTITY,
	BINARY_STEP,
	LOGISTIC,
	TAN_H,
	SOFTSIGN,
	RECTIFIED_LINEAR_UNIT,
	PARAMETERIC_RECTIFIED_LINEAR_UNIT,
	EXPONENTIAL_LINEAR_UNIT,
	SOFT_PLUS,
	BENT_IDENTITY,
	SOFT_EXPONENTIAL,
	SINUSOID,
	SINC,
	GAUSSIAN
}
